In [2]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(str)  # Error: Cannot convert 'Thirty' to int

print(df)



  Feature1  Feature2
0       10       5.5
1       20       6.7
2   Thirty       8.9


In [3]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
print(mean_value)
df.fillna(mean_value,inplace = True)  # Error: fillna() does not modify in place

print(df)


A    1.5
B    5.0
dtype: float64
     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [2]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([[1], [2], [3], [4], [5]])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

print(model.coef_)
print(model.intercept_)


[2.]
0.0


In [3]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[10, 20], [30, 40], [50,0]])  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.22474487  0.        ]
 [ 0.          1.22474487]
 [ 1.22474487 -1.22474487]]


In [33]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)

print(model.coef_)
print(model.intercept_)


[[0.02119793 0.10631366]]
[0.08511573]


C:\Users\Hxtreme\anaconda3\envs\AIML\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [1]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df)  # Error: Data should be reshaped
print(encoded)


  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


C:\Users\Hxtreme\anaconda3\envs\AIML\lib\site-packages\sklearn\preprocessing\_encoders.py:395: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  check_array(X, dtype=np.int)
C:\Users\Hxtreme\anaconda3\envs\AIML\lib\site-packages\sklearn\preprocessing\_encoders.py:110: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish t

In [5]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train, X_test, y_train, y_test)


[[3, 4], [5, 6], [1, 2]] [[7, 8]] [1, 0, 0] [1]


In [15]:
#7.from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

print(model.coef_)
print(model.intercept_)

[[0.02119793 0.10631366]]
[0.08511573]


C:\Users\Hxtreme\anaconda3\envs\AIML\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [30]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

imputer = SimpleImputer(strategy = 'mean')
X_train_impute = imputer.fit_transform(X_train)


model = LinearRegression()
model.fit(X_train_impute, y_train)  

print(model.coef_)
print(model.intercept_)


[2.5 2.5]
2.500000000000007


In [6]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed


model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print(model.feature_importances_)
print(model.max_features_)

[1. 0.]
2


C:\Users\Hxtreme\anaconda3\envs\AIML\lib\site-packages\sklearn\decomposition\online_lda.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  EPS = np.finfo(np.float).eps
C:\Users\Hxtreme\anaconda3\envs\AIML\lib\site-packages\sklearn\tree\tree.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and gu

In [9]:
#10.
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)


model = SVC()
model.fit(X_train_scaled, y_train)

new_model = ([[1, 150]])             # Unreliable output due to large-scale difference
scaler.transform(new_model)


array([[-1.22474487, -0.61237244]])